
logging:
  level:
    liquibase: INFO
    org.springframework.web: INFO

spring:
  application:
    name: ParadiseIslandApi
  profiles:
    active: dev
    include:
      - swagger

  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:mysql://localhost:3306/paradise_island?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  port: 8080
  servlet:
    context-path: /v1
